version: '3.7'

# Définition d'une configuration de logging par défaut 
x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '12m'
    max-file: '5'

# Définition d'une politique de redémarrage par défaut 
x-restart_policy:
  &defaut-restart_policy
  condition: any
  delay: 5s
  window: 120s
  max_attempts: 5

# Définition d'une configuration de mise à jour par défaut 
x-update_config:
  &defaut-update_config
  parallelism: 1
  delay: 5s
  failure_action: rollback
  monitor: 5s
  order: start-first

# Définition de ressources par défaut
x-resources:
  &defaut-resources
  limits:
    cpus: '1'
    memory: 1024M
  reservations:
    cpus: '0.05'
    memory: 100M

# Définition de contraintes de placement par défaut
x-placement:
  &defaut-placement
  constraints:
    - node.labels.env == ${env}

services:

# BDD Zabbix

  zabbix-db:
    image: ${zabbixdb_image_path}:${zabbixdb_image_tag}
    environment:
      POSTGRES_USER: ${zabbixdb_postgres_user}
      POSTGRES_PASSWORD: ${zabbixdb_postgres_password}
      POSTGRES_DB: ${zabbixdb_postgres_db}
    volumes:
      - ${zabbixdb_path_data}:/var/lib/postgresql/data
    networks:
      - zabbix-playground
    logging: *default-logging
    deploy:
      replicas: 1
      restart_policy: *defaut-restart_policy
      update_config: *defaut-update_config
      resources: *defaut-resources
      placement: *defaut-placement

# Server Zabbix

  zabbix-server:
    image: ${zabbixserver_image_path}:${zabbixserver_image_tag}
    hostname: 'zabbix-server'
    depends_on:
      - zabbix-db
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${zabbixdb_postgres_user}
      POSTGRES_PASSWORD: ${zabbixdb_postgres_password}
      POSTGRES_DB: ${zabbixdb_postgres_db}
      ZBX_CACHESIZE: '48M'
      ZBX_ALLOWUNSUPPORTEDDBVERSIONS: 1
    ports:
      - "${zabbixserver_port}:10051"
    volumes:
      - ${zabbixserver_path_data}:/var/lib/zabbix
    networks:
      - zabbix-playground
    logging: *default-logging
    deploy:
      replicas: 1
      restart_policy: *defaut-restart_policy
      update_config: *defaut-update_config
      resources: *defaut-resources
      placement: *defaut-placement

# Agent Zabbix

  zabbix-agent:
    image: ${zabbixagent_image_path}:${zabbixagent_image_tag}
    hostname: 'zabbix-agent2'
    depends_on:
      - zabbix-server
    privileged: true
    ports:
      - "10052:10050"
    environment:
      ZBX_HOSTNAME: 'zabbix-server'
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '${zabbixserver_port}'
      ZBX_SERVER_ACTIVE: zabbix-server
    networks:
      - zabbix-playground
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging: *default-logging
    deploy:
      mode : global
      restart_policy: *defaut-restart_policy
      update_config: *defaut-update_config
      resources: *defaut-resources
      placement: *defaut-placement

# Zabbix IW

  zabbix-web:
    image: ${zabbixweb_image_path}:${zabbixweb_image_tag}
    depends_on:
      - zabbix-db
      - zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${zabbixdb_postgres_user}
      POSTGRES_PASSWORD: ${zabbixdb_postgres_password}
      POSTGRES_DB: ${zabbixdb_postgres_db}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${zabbixweb_PHP_TZ}
#    ports:
#      - "${zabbixweb_frontend_port}:8080"
    volumes:
      - ${zabbixweb_path_data}:/usr/share/zabbix
    networks:
      - zabbix-playground
      - proxy
    logging: *default-logging
    deploy:
      replicas: 1
      restart_policy: *defaut-restart_policy
      update_config: *defaut-update_config
      resources: *defaut-resources
      placement: *defaut-placement
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.${app_servicename}.rule=Host(`$app_url`)"
        - "traefik.http.routers.${app_servicename}.entrypoints=websecure"
        - "traefik.http.routers.${app_servicename}.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.${app_servicename}.service=${app_servicename}-service"
        - "traefik.http.services.${app_servicename}-service.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  zabbix-playground:
    external: true
